/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIPackage;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phoeb
 */
public class NewGUI extends javax.swing.JFrame {
    
    private String name;
    private String iDnumber;
    private int age = 75;
    private String ageGroup = "Adult";
    private String dateofBirth;
    private String address;
    private String phone;
    private int rnum = 1;
    private String patronFile;
    private String oldFilename;
    private String[] arrLine;
    private String[] nameArr;
    private String[] idArr;
    private String[] ageArr;
    private String[] ageGroupArr;
    private String[] dobArr;
    private String[] addressArr;
    private String[] phoneArr;
    private String[] tempArr;
    private String [][] table;
    private String [] columns = {"#", "Name","Age", "Age Group", "DOB", "Address" , "Phone", "ID #"};
    private int editRemove;
    /**
     * Creates new form NewGUI
     */
    public NewGUI() throws FileNotFoundException {
        fileArr();
        
        initComponents();
        
        DefaultTableModel model = new DefaultTableModel(table, columns);
        jTable1.setModel(model);
        
        patronMenu();
        //jList1.setModel(new DefaultComboBoxModel<>(nameArr));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editPatronsM = new javax.swing.JPanel();
        editRemoveTitle = new javax.swing.JLabel();
        patronsTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        editRemoveinstruct = new javax.swing.JLabel();
        viewMenu = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        patronsMenu = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        addPatronMbutton = new javax.swing.JButton();
        removePatronMbutton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        editPatronMbutton = new javax.swing.JButton();
        searchPatronMbutton = new javax.swing.JButton();
        viewPatronMbutton = new javax.swing.JButton();
        addPatrons = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pDOB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pPhone = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        patronMenu = new javax.swing.JMenu();
        addPatronM = new javax.swing.JMenuItem();
        removePatronM = new javax.swing.JMenuItem();
        editPatronM = new javax.swing.JMenuItem();
        searchPatronM = new javax.swing.JMenuItem();
        viewPatronM = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editRemoveTitle.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        editRemoveTitle.setText("Edit Patrons");

        jTable1.setModel(new DefaultTableModel(table, columns));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout patronsTableLayout = new javax.swing.GroupLayout(patronsTable);
        patronsTable.setLayout(patronsTableLayout);
        patronsTableLayout.setHorizontalGroup(
            patronsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patronsTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap())
        );
        patronsTableLayout.setVerticalGroup(
            patronsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patronsTableLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        editRemoveinstruct.setText("Click on the part you wish to edit. ");

        javax.swing.GroupLayout editPatronsMLayout = new javax.swing.GroupLayout(editPatronsM);
        editPatronsM.setLayout(editPatronsMLayout);
        editPatronsMLayout.setHorizontalGroup(
            editPatronsMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPatronsMLayout.createSequentialGroup()
                .addGroup(editPatronsMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPatronsMLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(editRemoveTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editPatronsMLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(editRemoveinstruct)))
                .addContainerGap(395, Short.MAX_VALUE))
            .addGroup(editPatronsMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editPatronsMLayout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(patronsTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(82, Short.MAX_VALUE)))
        );
        editPatronsMLayout.setVerticalGroup(
            editPatronsMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPatronsMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editRemoveTitle)
                .addGap(68, 68, 68)
                .addComponent(editRemoveinstruct)
                .addContainerGap(538, Short.MAX_VALUE))
            .addGroup(editPatronsMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editPatronsMLayout.createSequentialGroup()
                    .addGap(127, 127, 127)
                    .addComponent(patronsTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(128, Short.MAX_VALUE)))
        );

        jLabel10.setText("View");

        jTable2.setModel(new DefaultTableModel(table, columns));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);
        jTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout viewMenuLayout = new javax.swing.GroupLayout(viewMenu);
        viewMenu.setLayout(viewMenuLayout);
        viewMenuLayout.setHorizontalGroup(
            viewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280))
        );
        viewMenuLayout.setVerticalGroup(
            viewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewMenuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addGap(66, 66, 66)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        patronsMenu.setBackground(new java.awt.Color(204, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Patrons Menu");

        addPatronMbutton.setText("Add Patrons");
        addPatronMbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPatronMbuttonMouseClicked(evt);
            }
        });
        addPatronMbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatronMbuttonActionPerformed(evt);
            }
        });

        removePatronMbutton.setText("Remove Patrons");
        removePatronMbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePatronMbuttonActionPerformed(evt);
            }
        });

        jLabel6.setText("Welcome to the Patrons Menu");

        editPatronMbutton.setText("Edit Patrons");
        editPatronMbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPatronMbuttonActionPerformed(evt);
            }
        });

        searchPatronMbutton.setText("Search Patrons");

        viewPatronMbutton.setText("View All Patrons");
        viewPatronMbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPatronMbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout patronsMenuLayout = new javax.swing.GroupLayout(patronsMenu);
        patronsMenu.setLayout(patronsMenuLayout);
        patronsMenuLayout.setHorizontalGroup(
            patronsMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patronsMenuLayout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addGroup(patronsMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(patronsMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addGroup(patronsMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchPatronMbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewPatronMbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editPatronMbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removePatronMbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(addPatronMbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        patronsMenuLayout.setVerticalGroup(
            patronsMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patronsMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(addPatronMbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(removePatronMbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(editPatronMbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(searchPatronMbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(viewPatronMbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Add Patron");

        jLabel2.setText("Enter Patron Name:");

        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });

        jLabel3.setText("Enter Patron Date of Birth:");

        pDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pDOBActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter Patron Address:");

        pAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAddressActionPerformed(evt);
            }
        });

        jLabel5.setText("Enter Patron Phone Number:");

        pPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pPhoneActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPatronsLayout = new javax.swing.GroupLayout(addPatrons);
        addPatrons.setLayout(addPatronsLayout);
        addPatronsLayout.setHorizontalGroup(
            addPatronsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPatronsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(addPatronsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addPatronsLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(pPhone))
                    .addGroup(addPatronsLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(pAddress))
                    .addGroup(addPatronsLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(pDOB))
                    .addGroup(addPatronsLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(addPatronsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPatronsLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)))))
                .addContainerGap(334, Short.MAX_VALUE))
            .addGroup(addPatronsLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(save)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addPatronsLayout.setVerticalGroup(
            addPatronsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPatronsLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(addPatronsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPatronsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPatronsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPatronsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(save)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseClicked(evt);
            }
        });

        patronMenu.setText("Patron Menu");
        patronMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patronMenuMouseClicked(evt);
            }
        });
        patronMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patronMenuActionPerformed(evt);
            }
        });

        addPatronM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        addPatronM.setText("Add Patron");
        addPatronM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPatronMMouseClicked(evt);
            }
        });
        addPatronM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatronMActionPerformed(evt);
            }
        });
        patronMenu.add(addPatronM);

        removePatronM.setText("Remove Patron");
        removePatronM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePatronMActionPerformed(evt);
            }
        });
        patronMenu.add(removePatronM);

        editPatronM.setText("Edit Patron");
        editPatronM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPatronMActionPerformed(evt);
            }
        });
        patronMenu.add(editPatronM);

        searchPatronM.setText("Search Patron");
        patronMenu.add(searchPatronM);

        viewPatronM.setText("View All Patrons");
        viewPatronM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPatronMActionPerformed(evt);
            }
        });
        patronMenu.add(viewPatronM);

        jMenuBar1.add(patronMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addPatrons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(patronsMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(editPatronsM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 57, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addPatrons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(patronsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 42, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(editPatronsM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(viewMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 42, Short.MAX_VALUE)))
        );

        setBounds(0, 0, 782, 670);
    }// </editor-fold>//GEN-END:initComponents

    public void addPatron() throws FileNotFoundException{
        Age patron = new Age(dateofBirth);
        age = patron.findAge();
        //age and age group
        if(age < 18){
            ageGroup = "Child";
        }
        
        else if(age>=18){
            ageGroup = "Adult";
        }
        
        
      
        
        
        //people.txt and temp.txt are opened
        File inputFile = new File("Patrons.txt");
        Scanner in = new Scanner(inputFile);
        PrintWriter out = new PrintWriter("temp.txt");
        
      
        rnum = 1;
        //read the input and write the output
        while(in.hasNextLine()){
            //replace all of the existing users
            out.println(in.nextLine());
            
            //increment rnum 
            rnum ++;
        }
        
        idCreate create = new idCreate();
        iDnumber = create.idCreate("000", "idList2.txt");
        
        
        Files replace = new Files( "temp2.txt" , "idList2.txt");
        replace.fileReplace();
        
        
        //print new user's information to temp.txt 
        out.println(rnum +  " _ " + name + " _ " + age + " _ " + ageGroup + " _ " + dateofBirth+ " _ " + address + " _ " + phone + " _ " + iDnumber);
        
        System.out.println(rnum +  " _ " + name + " _ " + age + " _ " + ageGroup + " _ " + dateofBirth+ " _ " + address + " _ " + phone + " _ " + iDnumber);
        //close both files so they are not cleared. 
        in.close();
        out.close();
        
        Files replace2 = new Files( "temp.txt" , "Patrons.txt");
        replace2.fileReplace();
        
        //creates file for movie. 
        
        patronFile = name + dateofBirth + "Id" + iDnumber; 
        //Trims whitespace and characters other than letters and numbers
        String rePlace = patronFile.replaceAll("[^a-zA-Z0-9]", "");
        patronFile = rePlace; 
        String tempString = patronFile + ".txt";
        patronFile = tempString;
        
        //Creates file with fileCreate 
        
        Files createP = new Files(patronFile);
        createP.fileCreate();
        
        
    }
    
    private void jMenuBar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseClicked
        // TODO add your handling code here:
        System.out.println("11111");
    }//GEN-LAST:event_jMenuBar1MouseClicked

    private void patronMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patronMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patronMenuActionPerformed

    private void patronMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patronMenuMouseClicked
        // TODO add your handling code here:
        patronMenu();
    }//GEN-LAST:event_patronMenuMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        if(pname.getText().isEmpty() || pDOB.getText().isEmpty() || pAddress.getText().isEmpty() || pPhone.getText().isEmpty()){
            name = "";
            dateofBirth = "";
            address = "";
            phone = "";
            new error().setVisible(true);
        }
        else{
            name = pname.getText();
            dateofBirth = pDOB.getText();
            address = pAddress.getText();
            phone = pPhone.getText();

            System.out.println(name + " " + dateofBirth + " " + address + " " + phone);

            //userInfo.setText("Name " + name + " DOB: " + dateofBirth + " Address: " + address + " Phone #: " + phone);
            pname.setText("");
            pDOB.setText("");
            pAddress.setText("");
            pPhone.setText("");

            try {
                addPatron();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(NewGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            String ageString = String.valueOf(age);
            patronInfo p = new patronInfo(name, ageString, ageGroup,dateofBirth, address, phone, iDnumber);
            p.patronI(name, ageString, ageGroup,dateofBirth, address, phone, iDnumber);

        }
    }//GEN-LAST:event_saveActionPerformed

    
    private void pPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pPhoneActionPerformed

    }//GEN-LAST:event_pPhoneActionPerformed

    private void pAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAddressActionPerformed

    }//GEN-LAST:event_pAddressActionPerformed

    private void pDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pDOBActionPerformed

    }//GEN-LAST:event_pDOBActionPerformed

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed

    }//GEN-LAST:event_pnameActionPerformed

    private void addPatronMbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatronMbuttonActionPerformed
        // TODO add your handling code here:
        addPatronMenu();
    }//GEN-LAST:event_addPatronMbuttonActionPerformed

    private void removePatronMbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePatronMbuttonActionPerformed
        // TODO add your handling code here:
        removePatronMenu();
    }//GEN-LAST:event_removePatronMbuttonActionPerformed

    private void addPatronMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPatronMMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addPatronMMouseClicked

    private void addPatronMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatronMActionPerformed
        // TODO add your handling code here:
        addPatronMenu();
    }//GEN-LAST:event_addPatronMActionPerformed

    private void removePatronMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePatronMActionPerformed
        // TODO add your handling code here:
        removePatronMenu();
    }//GEN-LAST:event_removePatronMActionPerformed

    private void addPatronMbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPatronMbuttonMouseClicked
        // TODO add your handling code here:
        addPatronMenu();
    }//GEN-LAST:event_addPatronMbuttonMouseClicked

    private void editPatronMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPatronMActionPerformed
        // TODO add your handling code here:
        editPatronMenu();
    }//GEN-LAST:event_editPatronMActionPerformed

    private void editPatronMbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPatronMbuttonActionPerformed
        // TODO add your handling code here:
        editPatronMenu();
    }//GEN-LAST:event_editPatronMbuttonActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MousePressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tb1Model = (DefaultTableModel)jTable1.getModel();
        
        int cValue = jTable1.getSelectedColumn();
        String selection = (String) tb1Model.getValueAt(jTable1.getSelectedRow(), cValue);
        System.out.println(selection);
        
        String n = (String)tb1Model.getValueAt(jTable1.getSelectedRow(),0);
        System.out.println(n);
        int number = Integer.parseInt(n);
        
        if(editRemove == 0){
            editPatronWindow editW = new editPatronWindow(number, cValue, selection);
            if(cValue == 0 || cValue == 2 || cValue == 3 || cValue == 7){
                System.out.println("error");
            }

            else{
                editW.editPWindow(number, cValue, selection);
            }
        }
        
        else if(editRemove == 1){
            //remove
            removePatronWindow removeW;
            try {
                removeW = new removePatronWindow(number);
                removeW.removePWindow(number);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(NewGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MousePressed

    private void viewPatronMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPatronMActionPerformed
        try {
            // TODO add your handling code here:
            viewMenu();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewPatronMActionPerformed

    private void viewPatronMbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPatronMbuttonActionPerformed
        
        
        try {
            viewMenu();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewPatronMbuttonActionPerformed

  
    public void addPatronMenu(){
        addPatrons.setVisible(true);
        patronsMenu.setVisible(false);
        editPatronsM.setVisible(false);
        patronsTable.setVisible(false);
        viewMenu.setVisible(false);
    }
    
    public void editPatronMenu(){
        editRemoveTitle.setText("Edit Patrons");
        editRemoveinstruct.setText("Click on the part of Patron You wish to edit. ");
        
        editRemove = 0;
        addPatrons.setVisible(false);
        patronsMenu.setVisible(false);
        editPatronsM.setVisible(true);
        patronsTable.setVisible(true);
        viewMenu.setVisible(false);
    }
    
    public void removePatronMenu(){
        editRemoveTitle.setText("Remove Patrons");
        editRemoveinstruct.setText("Click on the Patron You wish to remove. ");
        
        editRemove = 1;
        
        addPatrons.setVisible(false);
        patronsMenu.setVisible(false);
        editPatronsM.setVisible(true);
        patronsTable.setVisible(true);
        viewMenu.setVisible(false);
    }
    
    public void patronMenu(){
        addPatrons.setVisible(false);
        patronsMenu.setVisible(true);
        editPatronsM.setVisible(false);
        patronsTable.setVisible(false);
        viewMenu.setVisible(false);
    }
    
    public void viewMenu() throws FileNotFoundException{
        
        addPatrons.setVisible(false);
        patronsMenu.setVisible(false);
        editPatronsM.setVisible(false);
        patronsTable.setVisible(false); 
        viewMenu.setVisible(true);
    }
    
    public void fileArr()throws FileNotFoundException{
        
        File viewFile = new File("Patrons.txt");
        Scanner in = new Scanner(viewFile);
        
        int value = 100; 
        
        rnum = 0;
        nameArr = new String[value];
        idArr = new String[value];
        ageArr = new String[value];
        ageGroupArr = new String[value];
        dobArr = new String[value]; 
        addressArr = new String[value];
        phoneArr = new String[value];
        arrLine = new String[8];
        tempArr = new String[1];
        idArr = new String[value];
  
        while(in.hasNextLine()){
            String lineChange = in.nextLine();
            
            
            arrLine = lineChange.split("_");
            //System.out.println(arrLine[0]);
            
            nameArr[rnum] = arrLine[1];
            ageArr[rnum] = arrLine[2];
            ageGroupArr[rnum] = arrLine[3];
            dobArr[rnum] = arrLine[4];
            addressArr[rnum] = arrLine[5];
            phoneArr[rnum] = arrLine[6];
            idArr[rnum] = arrLine[7];
            
            
            //System.out.println(name[num]);
            //System.out.println(age[num]);
            
            rnum++;
          
        }
        
        
        table = new String[rnum][9];
        int count = 0;
        while(count < rnum){
            table[count][0] = Integer.toString(count+1);
            table[count][1] = nameArr[count];
            table[count][2] = ageArr[count];
            table[count][3] = ageGroupArr[count];
            table[count][4] = dobArr[count];
            table[count][5] = addressArr[count];
            table[count][6] = phoneArr[count];
            table[count][7] = idArr[count];
            count++;
        }
        
        
                
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NewGUI().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(NewGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addPatronM;
    private javax.swing.JButton addPatronMbutton;
    private javax.swing.JPanel addPatrons;
    private javax.swing.JMenuItem editPatronM;
    private javax.swing.JButton editPatronMbutton;
    private javax.swing.JPanel editPatronsM;
    private javax.swing.JLabel editRemoveTitle;
    private javax.swing.JLabel editRemoveinstruct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField pAddress;
    private javax.swing.JTextField pDOB;
    private javax.swing.JTextField pPhone;
    private javax.swing.JMenu patronMenu;
    private javax.swing.JPanel patronsMenu;
    private javax.swing.JPanel patronsTable;
    private javax.swing.JTextField pname;
    private javax.swing.JMenuItem removePatronM;
    private javax.swing.JButton removePatronMbutton;
    private javax.swing.JButton save;
    private javax.swing.JMenuItem searchPatronM;
    private javax.swing.JButton searchPatronMbutton;
    private javax.swing.JPanel viewMenu;
    private javax.swing.JMenuItem viewPatronM;
    private javax.swing.JButton viewPatronMbutton;
    // End of variables declaration//GEN-END:variables
}
