/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oldLibrary;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phoeb
 */
public class patronGUI extends javax.swing.JFrame {
    
    private String name;
    private String iDnumber;
    private int age = 75;
    private String ageGroup = "Adult";
    private String dateofBirth;
    private String address;
    private String phone;
    private int rnum = 1;
    private String patronFile;
    private String oldFilename;
    private String[] arrLine;
    private String[] nameArr;
    private String[] idArr;
    private String[] ageArr;
    private String[] ageGroupArr;
    private String[] dobArr;
    private String[] addressArr;
    private String[] phoneArr;
    private String[] tempArr;
    private String [][] table;
    private String [] columns = {"#", "Name","Age", "Age Group", "DOB", "Address" , "Phone", "ID #"};
    private int editRemove;
    private int response;
    private String searchReply;
    private ArrayList<String> searchResults = new ArrayList<String>();
    
    //
    private DefaultListModel dm = new DefaultListModel();
    
    private DefaultTableModel model = new DefaultTableModel(table, columns);
    /**
     * Creates new form NewGUI
     */
    public patronGUI() throws FileNotFoundException {
        
        
        initComponents();
        
        patronUpdate();
        
        fileArr();
        DefaultTableModel model = new DefaultTableModel(table, columns);
        jTable1.setModel(model);
        
        patronMenu();
        //jList1.setModel(new DefaultComboBoxModel<>(nameArr));
    }
    
    public void patronUpdate() throws FileNotFoundException{
        File inputFile = new File("Patrons.txt");
        Scanner in = new Scanner(inputFile);
        PrintWriter out = new PrintWriter("temp.txt");
        
      
        rnum = 1;
        //read the input and write the output
        while(in.hasNextLine()){
            //replace all of the existing users
            String lineChange = in.nextLine();
            

            arrLine = lineChange.split("_");
            
            Age patrons = new Age(arrLine[4]);
            age = patrons.findAge();
            //age and age group
            if(age < 18){
                ageGroup = "Child";
            }

            else if(age>=18){
                ageGroup = "Adult";
            }
                
            out.println(rnum + "_" + arrLine[1] + "_" + age + "_" + ageGroup + "_" + arrLine[4] + "_" + arrLine[5]+  "_" + arrLine[6] + "_" + arrLine[7]);
            rnum ++;
        }
        
        //close both files so they are not cleared. 
        in.close();
        out.close();
        
        Files replace = new Files( "temp.txt" , "Patrons.txt");
        replace.fileReplace();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchButtongroup = new javax.swing.ButtonGroup();
        searchMenu = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        searchBox = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        startSearch = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchResultsList = new javax.swing.JList<>();
        editPatronsM = new javax.swing.JPanel();
        editRemoveTitle = new javax.swing.JLabel();
        patronsTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        editRemoveinstruct = new javax.swing.JLabel();
        refreshEditTable = new javax.swing.JButton();
        viewMenu = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        patronsMenu = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        addPatronMbutton = new javax.swing.JButton();
        removePatronMbutton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        editPatronMbutton = new javax.swing.JButton();
        searchPatronMbutton = new javax.swing.JButton();
        viewPatronMbutton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        addPatrons = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pPhone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pDOB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pAddress = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        patronMenu = new javax.swing.JMenu();
        addPatronM = new javax.swing.JMenuItem();
        removePatronM = new javax.swing.JMenuItem();
        editPatronM = new javax.swing.JMenuItem();
        searchPatronM = new javax.swing.JMenuItem();
        viewPatronM = new javax.swing.JMenuItem();

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jLabel7.setText("Patrons Seacher");

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel9.setText("Click the catagory you want to search");

        searchButtongroup.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jRadioButton1.setText("Names");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        searchButtongroup.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jRadioButton2.setText("Ages");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        searchButtongroup.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jRadioButton3.setText("Age Group");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        searchButtongroup.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jRadioButton4.setText("DOB");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel11.setText("Search");

        startSearch.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        startSearch.setText("GO");
        startSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startSearchActionPerformed(evt);
            }
        });

        searchResultsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(searchResultsList);

        javax.swing.GroupLayout searchMenuLayout = new javax.swing.GroupLayout(searchMenu);
        searchMenu.setLayout(searchMenuLayout);
        searchMenuLayout.setHorizontalGroup(
            searchMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchMenuLayout.createSequentialGroup()
                .addGroup(searchMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchMenuLayout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchMenuLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel9))
                    .addGroup(searchMenuLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(searchMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchMenuLayout.createSequentialGroup()
                                .addGroup(searchMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2))
                                .addGap(18, 18, 18)
                                .addGroup(searchMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton4)))
                            .addGroup(searchMenuLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(searchMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(searchMenuLayout.createSequentialGroup()
                                        .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(startSearch))
                                    .addComponent(jScrollPane1))))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        searchMenuLayout.setVerticalGroup(
            searchMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(searchMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton4))
                .addGap(30, 30, 30)
                .addGroup(searchMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        editRemoveTitle.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        editRemoveTitle.setText("Edit Patrons");

        jTable1.setModel(new DefaultTableModel(table, columns));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout patronsTableLayout = new javax.swing.GroupLayout(patronsTable);
        patronsTable.setLayout(patronsTableLayout);
        patronsTableLayout.setHorizontalGroup(
            patronsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patronsTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap())
        );
        patronsTableLayout.setVerticalGroup(
            patronsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patronsTableLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        editRemoveinstruct.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        editRemoveinstruct.setText("Click on the part you wish to edit. ");

        refreshEditTable.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        refreshEditTable.setText("Refresh");
        refreshEditTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshEditTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editPatronsMLayout = new javax.swing.GroupLayout(editPatronsM);
        editPatronsM.setLayout(editPatronsMLayout);
        editPatronsMLayout.setHorizontalGroup(
            editPatronsMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPatronsMLayout.createSequentialGroup()
                .addGroup(editPatronsMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPatronsMLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(editRemoveinstruct))
                    .addGroup(editPatronsMLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(editRemoveTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(217, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPatronsMLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(refreshEditTable, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(302, 302, 302))
            .addGroup(editPatronsMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editPatronsMLayout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(patronsTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(82, Short.MAX_VALUE)))
        );
        editPatronsMLayout.setVerticalGroup(
            editPatronsMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPatronsMLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(editRemoveTitle)
                .addGap(76, 76, 76)
                .addComponent(editRemoveinstruct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 390, Short.MAX_VALUE)
                .addComponent(refreshEditTable, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(editPatronsMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editPatronsMLayout.createSequentialGroup()
                    .addGap(127, 127, 127)
                    .addComponent(patronsTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(128, Short.MAX_VALUE)))
        );

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jLabel10.setText("View Patrons");

        jTable2.setModel(new DefaultTableModel(table, columns));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);
        jTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout viewMenuLayout = new javax.swing.GroupLayout(viewMenu);
        viewMenu.setLayout(viewMenuLayout);
        viewMenuLayout.setHorizontalGroup(
            viewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(viewMenuLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(298, Short.MAX_VALUE))
        );
        viewMenuLayout.setVerticalGroup(
            viewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewMenuLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel10)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        patronsMenu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jLabel8.setText("Patrons Menu");

        addPatronMbutton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        addPatronMbutton.setText("Add Patrons");
        addPatronMbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPatronMbuttonMouseClicked(evt);
            }
        });
        addPatronMbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatronMbuttonActionPerformed(evt);
            }
        });

        removePatronMbutton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        removePatronMbutton.setText("Remove Patrons");
        removePatronMbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePatronMbuttonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel6.setText("Welcome to the Patrons Menu");

        editPatronMbutton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        editPatronMbutton.setText("Edit Patrons");
        editPatronMbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPatronMbuttonActionPerformed(evt);
            }
        });

        searchPatronMbutton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        searchPatronMbutton.setText("Search Patrons");
        searchPatronMbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPatronMbuttonActionPerformed(evt);
            }
        });

        viewPatronMbutton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        viewPatronMbutton.setText("View All Patrons");
        viewPatronMbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPatronMbuttonActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oldLibrary/dextercabin.gif"))); // NOI18N

        javax.swing.GroupLayout patronsMenuLayout = new javax.swing.GroupLayout(patronsMenu);
        patronsMenu.setLayout(patronsMenuLayout);
        patronsMenuLayout.setHorizontalGroup(
            patronsMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patronsMenuLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(patronsMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patronsMenuLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(patronsMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(patronsMenuLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(patronsMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(removePatronMbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addPatronMbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editPatronMbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchPatronMbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viewPatronMbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(patronsMenuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        patronsMenuLayout.setVerticalGroup(
            patronsMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patronsMenuLayout.createSequentialGroup()
                .addGroup(patronsMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(patronsMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(addPatronMbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(removePatronMbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(editPatronMbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(searchPatronMbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(viewPatronMbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oldLibrary/patronPic2.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jLabel1.setText("Add Patron");

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel2.setText("Enter Patron Name:");

        pname.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel3.setText("Enter Patron Date of Birth:");

        pPhone.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        pPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pPhoneActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel4.setText("Enter Patron Address:");

        pDOB.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        pDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pDOBActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel5.setText("Enter Patron Phone Number:");

        pAddress.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        pAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAddressActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel13.setText("Type your information into the boxes provided.");

        jLabel14.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel14.setText("Remember to click the save button when you are done.");

        jLabel15.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel15.setText("Enter the date of birth in MM/DD/YYYY format.");

        javax.swing.GroupLayout addPatronsLayout = new javax.swing.GroupLayout(addPatrons);
        addPatrons.setLayout(addPatronsLayout);
        addPatronsLayout.setHorizontalGroup(
            addPatronsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPatronsLayout.createSequentialGroup()
                .addGroup(addPatronsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPatronsLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(addPatronsLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(addPatronsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPatronsLayout.createSequentialGroup()
                                .addGroup(addPatronsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addGroup(addPatronsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(addPatronsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(pPhone)
                                        .addComponent(pname)
                                        .addComponent(pDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(addPatronsLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(addPatronsLayout.createSequentialGroup()
                                .addGroup(addPatronsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addGroup(addPatronsLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)))))
                .addContainerGap())
        );
        addPatronsLayout.setVerticalGroup(
            addPatronsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPatronsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(addPatronsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPatronsLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(addPatronsLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(addPatronsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(addPatronsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(35, 35, 35)
                .addGroup(addPatronsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addGroup(addPatronsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(47, 47, 47)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseClicked(evt);
            }
        });

        patronMenu.setText("Patron Menu");
        patronMenu.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        patronMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patronMenuMouseClicked(evt);
            }
        });
        patronMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patronMenuActionPerformed(evt);
            }
        });

        addPatronM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        addPatronM.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        addPatronM.setText("Add Patron");
        addPatronM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPatronMMouseClicked(evt);
            }
        });
        addPatronM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatronMActionPerformed(evt);
            }
        });
        patronMenu.add(addPatronM);

        removePatronM.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        removePatronM.setText("Remove Patron");
        removePatronM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePatronMActionPerformed(evt);
            }
        });
        patronMenu.add(removePatronM);

        editPatronM.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        editPatronM.setText("Edit Patron");
        editPatronM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPatronMActionPerformed(evt);
            }
        });
        patronMenu.add(editPatronM);

        searchPatronM.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        searchPatronM.setText("Search Patron");
        searchPatronM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPatronMActionPerformed(evt);
            }
        });
        patronMenu.add(searchPatronM);

        viewPatronM.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        viewPatronM.setText("View All Patrons");
        viewPatronM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPatronMActionPerformed(evt);
            }
        });
        patronMenu.add(viewPatronM);

        jMenuBar1.add(patronMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addPatrons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(patronsMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(editPatronsM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 57, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addPatrons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(patronsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 42, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(editPatronsM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(viewMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 42, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(searchMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 38, Short.MAX_VALUE)))
        );

        setBounds(0, 0, 782, 670);
    }// </editor-fold>//GEN-END:initComponents

    public void addPatron() throws FileNotFoundException{
        Age patron = new Age(dateofBirth);
        age = patron.findAge();
        //age and age group
        if(age < 18){
            ageGroup = "Child";
        }
        
        else if(age>=18){
            ageGroup = "Adult";
        }
        
        
      
        
        
        //people.txt and temp.txt are opened
        File inputFile = new File("Patrons.txt");
        Scanner in = new Scanner(inputFile);
        PrintWriter out = new PrintWriter("temp.txt");
        
      
        rnum = 1;
        //read the input and write the output
        while(in.hasNextLine()){
            //replace all of the existing users
            out.println(in.nextLine());
            
            //increment rnum 
            rnum ++;
        }
        
        idCreate create = new idCreate();
        iDnumber = create.idCreate("000", "idList2.txt");
        
        
        Files replace = new Files( "temp2.txt" , "idList2.txt");
        replace.fileReplace();
        
        
        //print new user's information to temp.txt 
        out.println(rnum +  "_" + name + "_" + age + "_" + ageGroup + "_" + dateofBirth+ "_" + address + "_" + phone + "_" + iDnumber);
        
        //System.out.println(rnum +  " _ " + name + " _ " + age + " _ " + ageGroup + " _ " + dateofBirth+ " _ " + address + " _ " + phone + " _ " + iDnumber);
        //close both files so they are not cleared. 
        in.close();
        out.close();
        
        Files replace2 = new Files( "temp.txt" , "Patrons.txt");
        replace2.fileReplace();
        
        //creates file for movie. 
        
        patronFile = name + dateofBirth + "Id" + iDnumber; 
        //Trims whitespace and characters other than letters and numbers
        String rePlace = patronFile.replaceAll("[^a-zA-Z0-9]", "");
        patronFile = rePlace; 
        String tempString = patronFile + ".txt";
        patronFile = tempString;
        
        //Creates file with fileCreate 
        
        Files createP = new Files(patronFile);
        createP.fileCreate();
        
        
    }
    
    private void jMenuBar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseClicked
        // TODO add your handling code here:
        //System.out.println("11111");
    }//GEN-LAST:event_jMenuBar1MouseClicked

    private void patronMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patronMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patronMenuActionPerformed

    private void patronMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patronMenuMouseClicked
        // TODO add your handling code here:
        patronMenu();
    }//GEN-LAST:event_patronMenuMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        if(pname.getText().isEmpty() || pPhone.getText().isEmpty() || pDOB.getText().isEmpty() || pAddress.getText().isEmpty()){
            name = "";
            dateofBirth = "";
            address = "";
            phone = "";
            new error().setVisible(true);
        }
        else{
            name = pname.getText();
            dateofBirth = pDOB.getText();
            address = pAddress.getText();
            phone = pPhone.getText();

            System.out.println(name + " " + dateofBirth + " " + address + " " + phone);

            //userInfo.setText("Name " + name + " DOB: " + dateofBirth + " Address: " + address + " Phone #: " + phone);
            pname.setText("");
            pPhone.setText("");
            pDOB.setText("");
            pAddress.setText("");

            try {
                addPatron();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(patronGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            String ageString = String.valueOf(age);
            patronInfo p;
            try {
                p = new patronInfo(name, ageString, ageGroup,dateofBirth, address, phone, iDnumber);
                p.patronI(name, ageString, ageGroup,dateofBirth, address, phone, iDnumber);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(patronGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            

        }
    }//GEN-LAST:event_saveActionPerformed

    
    private void pAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAddressActionPerformed

    }//GEN-LAST:event_pAddressActionPerformed

    private void pDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pDOBActionPerformed

    }//GEN-LAST:event_pDOBActionPerformed

    private void pPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pPhoneActionPerformed

    }//GEN-LAST:event_pPhoneActionPerformed

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed

    }//GEN-LAST:event_pnameActionPerformed

    private void addPatronMbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatronMbuttonActionPerformed
        // TODO add your handling code here:
        addPatronMenu();
    }//GEN-LAST:event_addPatronMbuttonActionPerformed

    private void removePatronMbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePatronMbuttonActionPerformed
        // TODO add your handling code here:
        removePatronMenu();
    }//GEN-LAST:event_removePatronMbuttonActionPerformed

    private void addPatronMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPatronMMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addPatronMMouseClicked

    private void addPatronMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatronMActionPerformed
        // TODO add your handling code here:
        addPatronMenu();
    }//GEN-LAST:event_addPatronMActionPerformed

    private void removePatronMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePatronMActionPerformed
        // TODO add your handling code here:
        removePatronMenu();
    }//GEN-LAST:event_removePatronMActionPerformed

    private void addPatronMbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPatronMbuttonMouseClicked
        // TODO add your handling code here:
        addPatronMenu();
    }//GEN-LAST:event_addPatronMbuttonMouseClicked

    private void editPatronMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPatronMActionPerformed
        // TODO add your handling code here:
        editPatronMenu();
    }//GEN-LAST:event_editPatronMActionPerformed

    private void editPatronMbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPatronMbuttonActionPerformed
        // TODO add your handling code here:
        editPatronMenu();
    }//GEN-LAST:event_editPatronMbuttonActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MousePressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tb1Model = (DefaultTableModel)jTable1.getModel();
        
        int cValue = jTable1.getSelectedColumn();
        String selection = (String) tb1Model.getValueAt(jTable1.getSelectedRow(), cValue);
        //System.out.println(selection);
        
        String n = (String)tb1Model.getValueAt(jTable1.getSelectedRow(),0);
        ///System.out.println(n);
        int number = Integer.parseInt(n);
        
        if(editRemove == 0){
            editPatronWindow editW = new editPatronWindow(number, cValue, selection);
            if(cValue == 0 || cValue == 2 || cValue == 3 || cValue == 7){
                //System.out.println("error");
                //NEED TO MAKE ERROR WINDOW
            }

            else{
                editW.editPWindow(number, cValue, selection);
            }
        }
        
        else if(editRemove == 1){
            //remove
            removePatronWindow removeW;
            try {
                removeW = new removePatronWindow(number);
                removeW.removePWindow(number);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(patronGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tb1Model = (DefaultTableModel)jTable2.getModel();
        
        name = (String) tb1Model.getValueAt(jTable2.getSelectedRow(), 1);
        String ageString = (String) tb1Model.getValueAt(jTable2.getSelectedRow(), 2);
        ageGroup = (String) tb1Model.getValueAt(jTable2.getSelectedRow(), 3);
        dateofBirth = (String) tb1Model.getValueAt(jTable2.getSelectedRow(), 4);
        address = (String) tb1Model.getValueAt(jTable2.getSelectedRow(), 5);
        phone = (String) tb1Model.getValueAt(jTable2.getSelectedRow(), 6);
        iDnumber = (String) tb1Model.getValueAt(jTable2.getSelectedRow(), 7);
        //System.out.println(selection);
        
        
        patronInfo p;
        try {
            p = new patronInfo(name, ageString, ageGroup,dateofBirth, address, phone, iDnumber);
            p.patronI(name, ageString, ageGroup,dateofBirth, address, phone, iDnumber);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(patronGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MousePressed

    private void viewPatronMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPatronMActionPerformed
        try {
            // TODO add your handling code here:
            viewMenu();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(patronGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewPatronMActionPerformed

    private void viewPatronMbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPatronMbuttonActionPerformed
        
        
        try {
            viewMenu();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(patronGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewPatronMbuttonActionPerformed

    private void searchPatronMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPatronMActionPerformed
        // TODO add your handling code here:
        searchPatronMenu();
    }//GEN-LAST:event_searchPatronMActionPerformed

    private void searchPatronMbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPatronMbuttonActionPerformed
        // TODO add your handling code here:
        searchPatronMenu();
    }//GEN-LAST:event_searchPatronMbuttonActionPerformed

    private void startSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startSearchActionPerformed
        searchReply = searchBox.getText();
        try {
            // TODO add your handling code here:
            searchPatrons();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(patronGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_startSearchActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        response = 1;
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        response = 2;
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        response = 3;
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        response = 4;
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void refreshEditTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshEditTableActionPerformed
        try {
            // TODO add your handling code here:
            fileArr();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(patronGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        model = new DefaultTableModel(table, columns);
        jTable1.setModel(model);
        
    }//GEN-LAST:event_refreshEditTableActionPerformed

    
    
    public void searchPatrons() throws FileNotFoundException{
        rnum = 0;
        
        File inputFile = new File("Patrons.txt");
        Scanner in = new Scanner(inputFile);
        
        int value = 100; 
        
        
        nameArr = new String[value];
        idArr = new String[value];
        ageArr = new String[value];
        ageGroupArr = new String[value];
        dobArr = new String[value]; 
        addressArr = new String[value];
        phoneArr = new String[value];
        arrLine = new String[8];
        tempArr = new String[1];
        idArr = new String[value];
  
        while(in.hasNextLine()){
            String lineChange = in.nextLine();
            
            
            arrLine = lineChange.split("_");
            //System.out.println(arrLine[0]);
            
            nameArr[rnum] = arrLine[1];
            ageArr[rnum] = arrLine[2];
            ageGroupArr[rnum] = arrLine[3];
            dobArr[rnum] = arrLine[4];
            addressArr[rnum] = arrLine[5];
            phoneArr[rnum] = arrLine[6];
            idArr[rnum] = arrLine[7];
            
            //System.out.println(name[num]);
            //System.out.println(age[num]);
            
            rnum++;
          
        }
        
        searchResultsList.setModel(dm);
        
        //director searcher
        if(response == 1){


            String split[] = searchReply.split(" ", 0);
            for(String resp1: split){

                String temp1 = resp1.toLowerCase();
                resp1 = temp1;

                temp1 = resp1.replaceAll("^a-z0-9", "");
                resp1 = temp1; 

                //System.out.println("in " + resp2);


                int count = 0;
                int num = 1;
                while(count < rnum){

                    tempArr[0] = nameArr[count];

                    String directorNew = Arrays.toString(tempArr);

                    String spliter[] = directorNew.split(" ", 0);

                    for(String dNew: spliter){
                        String temp;

                        temp = dNew.toLowerCase();
                        dNew = temp; 

                        //non letters and spaces remove
                        temp = dNew.replaceAll("[^a-z0-9]", "");
                        dNew = temp;
                        //System.out.println("arr " + dNew);

                        if(resp1.equals(dNew)){
                            dm.addElement(num + " _ " + nameArr[count] + " - " + ageArr[count] + " - " + ageGroupArr[count] + " - " + dobArr[count] + " - " + addressArr[count]+ " - " + phoneArr[count] + " - " + idArr[count]);
                            //loans.println(num + " _ " + nameArr[count] + " _ " + ageArr[count] + " _ " + ageGroupArr[count] + " _ " + dobArr[count] + " _ " + addressArr[count]+ " _ " + phoneArr[count] + " _ " + idArr[count]);
                           
                            num++;
                        }


                    }
                    count++;
                }

            }
            

        }

        //director searcher
        if(response == 2){
            int ageInt = Integer.parseInt(searchReply);

            int count = 0;
            int num = 1;



            while(count  < rnum){

                tempArr[0] = ageArr[count];

                String dateNew = Arrays.toString(tempArr);
                String temp;
                temp = dateNew.replaceAll("[^0-9]", "");
                dateNew = temp;

                int intAge = Integer.parseInt(dateNew);

                if(ageInt == intAge){
                    dm.addElement(num + " _ " + nameArr[count] + " - " + ageArr[count] + " - " + ageGroupArr[count] + " - " + dobArr[count] + " - " + addressArr[count]+ " - " + phoneArr[count] + " - " + idArr[count]);
                    //loans.println(num + " _ " + nameArr[count] + " _ " + ageArr[count] + " _ " + ageGroupArr[count] + " _ " + dobArr[count] + " _ " + addressArr[count]+ " _ " + phoneArr[count] + " _ " + idArr[count]);
                    num++;
                }
                count++;

            }


        }

        //age searcher
        if(response == 3){

            String split[] = searchReply.split(" ", 0);
            for(String resp1: split){

                String temp1 = resp1.toLowerCase();
                resp1 = temp1;

                temp1 = resp1.replaceAll("^a-z0-9", "");
                resp1 = temp1; 

                //System.out.println("in " + resp2);


                int count = 0;
                int num = 1;
                while(count < rnum){

                    tempArr[0] = ageGroupArr[count];

                    String directorNew = Arrays.toString(tempArr);

                    String spliter[] = directorNew.split(" ", 0);

                    for(String dNew: spliter){
                        String temp;

                        temp = dNew.toLowerCase();
                        dNew = temp; 

                        //non letters and spaces remove
                        temp = dNew.replaceAll("[^a-z0-9]", "");
                        dNew = temp;
                        //System.out.println("arr " + dNew);

                        if(resp1.equals(dNew)){
                            dm.addElement(num + " _ " + nameArr[count] + " - " + ageArr[count] + " - " + ageGroupArr[count] + " - " + dobArr[count] + " - " + addressArr[count]+ " - " + phoneArr[count] + " - " + idArr[count]);
                            //loans.println(num + " _ " + nameArr[count] + " _ " + ageArr[count] + " _ " + ageGroupArr[count] + " _ " + dobArr[count] + " _ " + addressArr[count]+ " _ " + phoneArr[count] + " _ " + idArr[count]);
                            num++;
                        }


                    }
                    count++;
                }

            }



        }

        if(response == 4){


            searchReply = searchReply.replaceAll("[^0-9]", "");


            int num = 1;
            int count = 0;

            while(count < rnum){

                tempArr[0] = dobArr[count];

                String nameNew = Arrays.toString(tempArr);
                String temp;

                //non letters and spaces remove
                temp = nameNew.replaceAll("[^0-9]", "");
                nameNew = temp;




                if(searchReply.equals(nameNew)){
                    dm.addElement(num + " _ " + nameArr[count] + " - " + ageArr[count] + " - " + ageGroupArr[count] + " - " + dobArr[count] + " - " + addressArr[count]+ " - " + phoneArr[count] + " - " + idArr[count]);
                    //loans.println(num + " _ " + nameArr[count] + " _ " + ageArr[count] + " _ " + ageGroupArr[count] + " _ " + dobArr[count] + " _ " + addressArr[count]+ " _ " + phoneArr[count] + " _ " + idArr[count]);
                }   num++;
                count++;
            }


        }

        
     in.close();
       
    }
  
    
    public void searchPatronMenu(){
        addPatrons.setVisible(false);
        patronsMenu.setVisible(false);
        editPatronsM.setVisible(false);
        patronsTable.setVisible(false);
        viewMenu.setVisible(false);
        searchMenu.setVisible(true);
        
    }
    public void addPatronMenu(){
        addPatrons.setVisible(true);
        patronsMenu.setVisible(false);
        editPatronsM.setVisible(false);
        patronsTable.setVisible(false);
        viewMenu.setVisible(false);
        searchMenu.setVisible(false);
    }
    
    public void editPatronMenu(){
        editRemoveTitle.setText("Edit Patrons");
        editRemoveinstruct.setText("Click on the part of Patron You wish to edit. ");
        
        editRemove = 0;
        addPatrons.setVisible(false);
        patronsMenu.setVisible(false);
        editPatronsM.setVisible(true);
        patronsTable.setVisible(true);
        viewMenu.setVisible(false);
        searchMenu.setVisible(false);
    }
    
    public void removePatronMenu(){
        editRemoveTitle.setText("Remove Patrons");
        editRemoveinstruct.setText("Click on the Patron You wish to remove. ");
        
        editRemove = 1;
        
        addPatrons.setVisible(false);
        patronsMenu.setVisible(false);
        editPatronsM.setVisible(true);
        patronsTable.setVisible(true);
        viewMenu.setVisible(false);
        searchMenu.setVisible(false);
    }
    
    public void patronMenu(){
        addPatrons.setVisible(false);
        patronsMenu.setVisible(true);
        editPatronsM.setVisible(false);
        patronsTable.setVisible(false);
        viewMenu.setVisible(false);
        searchMenu.setVisible(false);
    }
    
    public void viewMenu() throws FileNotFoundException{
        fileArr();
        model = new DefaultTableModel(table, columns);
        jTable2.setModel(model);
        
        
        
        addPatrons.setVisible(false);
        patronsMenu.setVisible(false);
        editPatronsM.setVisible(false);
        patronsTable.setVisible(false); 
        viewMenu.setVisible(true);
        searchMenu.setVisible(false);
    }
    
    public void fileArr()throws FileNotFoundException{
        
        File viewFile = new File("Patrons.txt");
        Scanner in = new Scanner(viewFile);
        
        int value = 100; 
        
        rnum = 0;
        nameArr = new String[value];
        idArr = new String[value];
        ageArr = new String[value];
        ageGroupArr = new String[value];
        dobArr = new String[value]; 
        addressArr = new String[value];
        phoneArr = new String[value];
        arrLine = new String[8];
        tempArr = new String[1];
        idArr = new String[value];
  
        while(in.hasNextLine()){
            String lineChange = in.nextLine();
            
            
            arrLine = lineChange.split("_");
            //System.out.println(arrLine[0]);
            
            nameArr[rnum] = arrLine[1];
            ageArr[rnum] = arrLine[2];
            ageGroupArr[rnum] = arrLine[3];
            dobArr[rnum] = arrLine[4];
            addressArr[rnum] = arrLine[5];
            phoneArr[rnum] = arrLine[6];
            idArr[rnum] = arrLine[7];
            
            
            //System.out.println(name[num]);
            //System.out.println(age[num]);
            
            rnum++;
          
        }
        
        
        table = new String[rnum][9];
        int count = 0;
        while(count < rnum){
            table[count][0] = Integer.toString(count+1);
            table[count][1] = nameArr[count];
            table[count][2] = ageArr[count];
            table[count][3] = ageGroupArr[count];
            table[count][4] = dobArr[count];
            table[count][5] = addressArr[count];
            table[count][6] = phoneArr[count];
            table[count][7] = idArr[count];
            count++;
        }
        
        
                
    }
    /**
     * @param args the command line arguments
     */
    public void runPatron() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patronGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patronGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patronGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patronGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new patronGUI().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(patronGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addPatronM;
    private javax.swing.JButton addPatronMbutton;
    private javax.swing.JPanel addPatrons;
    private javax.swing.JMenuItem editPatronM;
    private javax.swing.JButton editPatronMbutton;
    private javax.swing.JPanel editPatronsM;
    private javax.swing.JLabel editRemoveTitle;
    private javax.swing.JLabel editRemoveinstruct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField pAddress;
    private javax.swing.JTextField pDOB;
    private javax.swing.JTextField pPhone;
    private javax.swing.JMenu patronMenu;
    private javax.swing.JPanel patronsMenu;
    private javax.swing.JPanel patronsTable;
    private javax.swing.JTextField pname;
    private javax.swing.JButton refreshEditTable;
    private javax.swing.JMenuItem removePatronM;
    private javax.swing.JButton removePatronMbutton;
    private javax.swing.JButton save;
    private javax.swing.JTextField searchBox;
    private javax.swing.ButtonGroup searchButtongroup;
    private javax.swing.JPanel searchMenu;
    private javax.swing.JMenuItem searchPatronM;
    private javax.swing.JButton searchPatronMbutton;
    private javax.swing.JList<String> searchResultsList;
    private javax.swing.JToggleButton startSearch;
    private javax.swing.JPanel viewMenu;
    private javax.swing.JMenuItem viewPatronM;
    private javax.swing.JButton viewPatronMbutton;
    // End of variables declaration//GEN-END:variables
}
