/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oldLibrary;

/**
 *
 * @author jacqu
 */
public class ProgramDeletingConfirmation extends javax.swing.JFrame {
    private Program program;

    /**
     * Creates new form ProgramDeletingConfirmation
     */
    public ProgramDeletingConfirmation(Program pro) {
        initComponents();
        program = pro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        confirmationBtn = new javax.swing.JButton();
        deletedProgram = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel1.setText("Delete Program Confirmation");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel2.setText("You are Deleting: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel3.setText("Are you sure you want to delete this?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        confirmationBtn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        confirmationBtn.setText("Confirm");
        confirmationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmationBtnActionPerformed(evt);
            }
        });
        getContentPane().add(confirmationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        deletedProgram.setEditable(false);
        deletedProgram.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        deletedProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletedProgramActionPerformed(evt);
            }
        });
        getContentPane().add(deletedProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 180, 50));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        setSize(new java.awt.Dimension(660, 513));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deletedProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletedProgramActionPerformed
        deletedProgram.setText(String.valueOf(program));
    }//GEN-LAST:event_deletedProgramActionPerformed

    private void confirmationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmationBtnActionPerformed
        ProgramDataStore.Programs.remove(program);
        ProgramDeletingConfirmation confirm = new ProgramDeletingConfirmation(program);
        confirm.setVisible(false);
    }//GEN-LAST:event_confirmationBtnActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmationBtn;
    private javax.swing.JTextField deletedProgram;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
