/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cs234project;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jacqu
 */
public class EmployeeAddFrame extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeAddFrame
     */
    public EmployeeAddFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        phoneNumberField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        dobField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        positionField = new javax.swing.JTextField();
        salaryField = new javax.swing.JTextField();
        idField = new javax.swing.JTextField();
        hoursField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel1.setText("Add an Employee");
        MainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel7.setText("Date of Birth (MMDDYYYY) : ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 364, -1, 30));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel8.setText("Address");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel9.setText("Phone Number:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, -1, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel6.setText("Name");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 293, -1, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel4.setText("Salary");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel3.setText("Employee ID:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 93, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel2.setText("Weekly Hours Worked:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 27, -1, 20));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel5.setText("Position");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        phoneNumberField.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        phoneNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberFieldActionPerformed(evt);
            }
        });
        jPanel2.add(phoneNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 160, 40));

        addressField.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jPanel2.add(addressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 160, 40));

        dobField.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jPanel2.add(dobField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 160, 40));

        nameField.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jPanel2.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 160, 40));

        positionField.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jPanel2.add(positionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 160, 40));

        salaryField.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jPanel2.add(salaryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 160, 40));

        idField.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jPanel2.add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 160, 40));

        hoursField.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        hoursField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursFieldActionPerformed(evt);
            }
        });
        jPanel2.add(hoursField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 160, 40));

        MainPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 610, 580));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 38, 70, 40));

        MainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 760, 400, 110));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\jacqu\\Downloads\\employees.png")); // NOI18N
        MainPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 0, 220, 160));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 851));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String nameValue = (nameField.getText());
        int hoursValue = Integer.parseInt(hoursField.getText());
        String idValue = (idField.getText());
        double salaryValue = Double.parseDouble(salaryField.getText());
        String positionValue = positionField.getText();
        int dob = Integer.parseInt(dobField.getText());
        String address = addressField.getText();
        String phoneNumber = phoneNumberField.getText();
        Employee emplo = new Employee(hoursValue, idValue, salaryValue, positionValue, nameValue, dob, address, phoneNumber);
       
        
        int answer = JOptionPane.showConfirmDialog(null, "Are you sure you want to add the employee named : " + emplo.name +  " ?", "Delete Confirmation", JOptionPane.YES_NO_OPTION);
            
            if(answer == 0){
                
                 EmployeeDataStore.Employees.add(emplo);
                 dispose();
            }
                
    }//GEN-LAST:event_btnAddActionPerformed

    private void hoursFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursFieldActionPerformed

    private void phoneNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeAddFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTextField addressField;
    public static javax.swing.JButton btnAdd;
    private javax.swing.JTextField dobField;
    private javax.swing.JTextField hoursField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JTextField positionField;
    private javax.swing.JTextField salaryField;
    // End of variables declaration//GEN-END:variables
}
