/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guilibrary;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author phoeb
 */
public class editPatronWindow extends javax.swing.JFrame {

    private String reply;
    private String type;
    private String thing;
    
    private int age = 75;
    private String ageGroup = "Adult";
    
    private int rnum = 1;
    private String patronFile;
    private String oldFilename;
    private String[] arrLine;
    
    
    private int resp;
    private int cValue;
    
    /**
     * Creates new form editPatronWindow
     */
    public editPatronWindow(int num, int cValue, String select) {
        if(cValue == 1){
            type = "name";
                    
        }

        if(cValue == 4){
            type = "DOB";
        }

        if(cValue == 5){
            type = "address";
        }

        if(cValue == 6){
            type = "phone #";
        }
        
        thing = select;
        
        initComponents();
        
        
        type1.setText(type);
        type2.setText(type);
        type3.setText(type);
        
        thing1.setText(thing);
        
        resp = num;
        this.cValue = cValue;
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        instructions = new javax.swing.JLabel();
        response = new javax.swing.JTextField();
        editingInstruct = new javax.swing.JLabel();
        currentItemis = new javax.swing.JLabel();
        thing1 = new javax.swing.JLabel();
        saveEdit = new javax.swing.JButton();
        type1 = new javax.swing.JLabel();
        type2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        type3 = new javax.swing.JLabel();

        jLabel1.setText("Paton Editing");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        instructions.setText("Please type your new");

        editingInstruct.setText("You are editing");

        currentItemis.setText("Your current ");

        thing1.setText("thing");

        saveEdit.setText("Save");
        saveEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEditActionPerformed(evt);
            }
        });

        type1.setText("type");

        type2.setText("type");

        jLabel4.setText("is");

        type3.setText("type");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(instructions)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(type3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(response, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(editingInstruct)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(type1))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(currentItemis)
                                        .addGap(2, 2, 2)
                                        .addComponent(type2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(thing1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(saveEdit)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editingInstruct)
                    .addComponent(type1))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentItemis)
                    .addComponent(thing1)
                    .addComponent(type2)
                    .addComponent(jLabel4))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(response, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type3))
                .addGap(18, 18, 18)
                .addComponent(saveEdit)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEditActionPerformed
        // TODO add your handling code here:
        
        if(response.getText().isEmpty()){
            reply = "";
            
            new error().setVisible(true);
        }
        else{
            reply = response.getText();
            reply = reply.replaceAll("\\s+$", "");

            //System.out.println(reply);

            //userInfo.setText("Name " + name + " DOB: " + dateofBirth + " Address: " + address + " Phone #: " + phone);
            response.setText("");
            
            try {
                editPatron();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(editPatronWindow.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(editPatronWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
    }//GEN-LAST:event_saveEditActionPerformed

    public void editPatron() throws FileNotFoundException, InterruptedException{
        rnum = 0;
        File inputFileC = new File("Patrons.txt");
        Scanner inCount = new Scanner(inputFileC);
        
        while(inCount.hasNextLine()){ 
            String next = inCount.nextLine();
            rnum++;
        }
        
        inCount.close();
        
        resp--;
        
        File inputFile = new File("Patrons.txt");
        Scanner in = new Scanner(inputFile);
        PrintWriter out = new PrintWriter("temp.txt");
        
        int count = 0;
        while(count < rnum && in.hasNextLine()){
            //System.out.println(count);
            String lineChange = in.nextLine();
            //System.out.println(lineChange);
                
            if(count == resp){
                
                arrLine = lineChange.split("_");
                
                //find file name 
                oldFilename = arrLine[1] + arrLine[4] + "Id" + arrLine[7]; 
                String rePlace2 = oldFilename.replaceAll("[^a-zA-Z0-9]", "");
                oldFilename = rePlace2;
                String temp3 = oldFilename +".txt";
                oldFilename = temp3; 
               
                if(cValue == 1){
                    
                    arrLine[1] = reply;
                    //System.out.println("name is@" + arrLine[1]);
                }
                
                if(cValue == 4){
                    arrLine[4] = reply;
                    //System.out.println("The new DOB is: " + arrLine[4]);
                    
                }
                
                if(cValue == 5){
                    arrLine[5] = reply;
                    //System.out.println("The new address is: " + arrLine[5]);
                    
                }
                
                if(cValue == 6){
                    arrLine[6] = reply;
                    //System.out.println("The new phone is: " + arrLine[6]);
                    
                }
                
                    
                Age patron = new Age(arrLine[4]);
                age = patron.findAge();
                //age and age group
                if(age < 18){
                    ageGroup = "Child";
                }

                else if(age>=18){
                    ageGroup = "Adult";
                }
                
                out.println(count+1 + " _" + arrLine[1] + "_" + age + "_" + ageGroup + "_" + arrLine[4] + "_" + arrLine[5]+  "_" + arrLine[6] +  "_" + arrLine[7]);
                
                
                //System.out.println("Printing" + count+1 + " _" + arrLine[1] + "_" + age + "_" + ageGroup + "_" + arrLine[4] + "_" + arrLine[5]+  "_" + arrLine[6] +  "_" + arrLine[7]);
                
                String iD;
                iD = arrLine[1] + arrLine[4] + "Id" + arrLine[7]; 
                //Trims whitespace and characters other than letters and numbers
                String rePlace = iD.replaceAll("[^a-zA-Z0-9]", "");
                iD = rePlace; 
                String temp = iD + ".txt";
                iD = temp;

                //Creates file with fileCreate
                Files editF = new Files(iD,oldFilename);
                if(oldFilename != iD){
                    editF.fileCreate();

                    //editF.fileReplace();
                }
                count++;
            }
            
            else{
                out.println(lineChange);
                //System.out.println("keep " + in.nextLine());
                count ++;
                //System.out.println("else");
            }
            
        }
        in.close();
        out.close();
        
        Files replace = new Files( "temp.txt" , "Patrons.txt");
        replace.fileReplace();
        
    }
    
    /**
     * @param args the command line arguments
     */
    public void editPWindow(int num, int column, String select){
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editPatronWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editPatronWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editPatronWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editPatronWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editPatronWindow(num, column, select).setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentItemis;
    private javax.swing.JLabel editingInstruct;
    private javax.swing.JLabel instructions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField response;
    private javax.swing.JButton saveEdit;
    private javax.swing.JLabel thing1;
    private javax.swing.JLabel type1;
    private javax.swing.JLabel type2;
    private javax.swing.JLabel type3;
    // End of variables declaration//GEN-END:variables
}
